baseURL = "https://blog.enaium.cn"
defaultContentLanguage = "zh"

[languages]
[languages.zh]
languageName = "简体中文"
weight = 0
contentDir = "content/zh"
[languages.zh.params]
title = "Enaium的博客"

[languages.en]
languageName = "English"
weight = 1
contentDir = "content/en"
[languages.en.params]
title = "Enaium's Blog"
